#!/usr/bin/env bash
# To check if parametees are not less than 3

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_path="$4"

# to Check if ssh path is provided else use default
if [ -z "$ssh_path" ]; then
	scp -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
else
	scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username@$server_ip:~/"
fi
