#!/usr/bin/env bash
# Script that configures a new Ubuntu machine
# so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install -y nginx

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\\/\\/www.youtube.com\\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
