#!/usr/bin/env bash
# Creating a custome 404 page
# Script that configures a new Ubuntu machine

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Creating a HTML file that displays Hello world
echo "Hello World!" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

# Replace the default server_name with a custom redirect
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\\/\\/www.youtube.com\\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Replace the default server configuration with a custom 404 configuration
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart
