#!/usr/bin/env bash
# Configuring Nginx so that its HTTP response has  a custom header
# Updating package lists and installing nginx
apt-get update
apt-get install -y nginx

# Allowing Nginx HTTP traffic
ufw allow "Nginx HTTP"

# Creating a HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Creating a webpage for error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Creating a custom header with hostname
sed -i '/server_name _;/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-enabled/default

# Replace the default server_name with a custom redirect
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\\/\\/www.youtube.com\\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Replace the default server configuration with a custom 404 configuration
string_to_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/listen 80 default_server;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
service nginx restart
