#!/usr/bin/env bash
# Bash script Configures HAproxy in Ubuntu machine so it sends traffic to web-01 and web-02
# Update the package lists and install Haproxy
apt-get update
apt-get install -y haproxy

# Configure HAProxy
echo '
frontend http-in
	bind *:80
	default_backend webservers

backend webservers
	balance roundrobin
	server web-01 54.197.21.126:80 check
	server web-02 54.236.56.228:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy
service haproxy restart
