#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd
# it only displays:
# username
# user id
# home directory path for the user

while IFS=":" read -r LINE
do
	echo "$LINE" | cut -d':' -f1,4,7
done < "/etc/passwd"
