#!/usr/bin/env bash

while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIR COMMAND_SHELL
do
	echo " The user $USERNAME is part of the $GROUP_ID gang,"\
		"lives in $HOME_DIR and rides $COMMAND_SHELL."\
		"$USER_ID's place is protected by the passcode $PASSWORD,"\
	       "more info about the user here: $USER_ID_INFO"
       done < "/etc/passwd"
