#!/usr/bin/env bash
# This Script displays "Best School" 10 times 
# But for the 9th iteration displays "Best School and then Hi in new line

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 9 ];
	then
		echo "Hi"
		echo "Best School"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
