#!/usr/bin/env bash
# This script configures an Ubuntu server:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.temp
echo "127.0.0.2		localhost" > ~/hosts.temp
echo "8.8.8.8		facebook.com" >> ~/hosts.temp
cp -f ~/hosts.temp /etc/hosts
