#!/usr/bin/env bash
# This script configures an Ubuntu server:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/temp_hosts
sudo echo "127.0.0.2		localhost" > ~/temp_hosts
sudo echo "8.8.8.8		facebook.com" >> ~/temp_hosts
sudo cp -f ~/temp_hosts /etc/hosts
