#!/usr/bin/env bash
# This script fixes a web server to run Nginx as nginx user port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/listen 80 default_server/listen 8080 default_server/g" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
